### ISSUE TITLE
发布时报：网络出现问题

### ISSUE THREAD

**Issue by hanting001** [aliyun-UED/open5#2]
PUT http://test.oss-cn-shanghai.aliyuncs.com/publish/demo.json 403 (Forbidden)

**Comment by chylvina** [comment]
可以使用了，抱歉。

**Comment by KevenYoung** [comment]
@chylvina 好像现在还是这样啊，保存和发布看着没啥区别啊，但是保存没事儿，发布就会403
线上的 demo 也是啊，点发布就 403，很神奇
